---
abstract: 'Session store container which provides transparent access'
author:
  - 'Ichito Nagata <i.nagata110@gmail.com>'
build_requires:
  Plack::Session::Store: 0.20
  Test::Exception: 0.32
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Session-Store-Transparent
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Session::Store::Transparent:
    file: lib/Plack/Session/Store/Transparent.pm
    version: 0.03
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/i110/p5-Plack-Session-Store-Transparent/issues
  homepage: https://github.com/i110/p5-Plack-Session-Store-Transparent
  repository: git://github.com/i110/p5-Plack-Session-Store-Transparent.git
version: 0.03
